---
- name: Get updated files from git repository 
  git: 
    repo: "https://github.com/RomeHein/HomeInOne.git"
    dest: /opt/homeinone

- name: build the image
  command: docker build -t homeinone /opt/homeinone --build-arg api_port={{api_port}}

- name: Template docker-compose.yml
  template:
    src: docker-compose.yml.j2
    dest: /opt/homeinone/docker-compose.yml

- name: Start up HomeIn1
  command: docker-compose up -d
  args:
    chdir: /opt/homeinone